### ISSUE TITLE
Trouble dragging the map

### ISSUE THREAD

**Issue by Stemby** [prusnak/coinmap#72]
Quoting form [here](https://bitcointalk.org/index.php?topic=175900.msg10301037#msg10301037):

> Quote from: Newar on January 29, 2015, 05:40:18 PM
>> Quote from: amincd on January 29, 2015, 09:00:48 AM
>> I'm having trouble dragging the map to navigate it. It didn't have this problem before.
>
>Me too. Actually the first drag is ok, but once I click one of the circles, I can't drag anymore. This was working fine just a few hours ago.

Thank you!

**Comment by prusnak** [comment]
Fixed.
